import numpy as np
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print('a:')
print(a)
print('b:')
print(b)
print('a - b = :')
print(a - b)
print('a * b = :')
print(a * b)
print('a ** b = :')
print(a ** b)
print('10 * np.sin(a) = :')
print(10 * np.sin(a))
print('a < 35 :')
print(a < 35)

A = np.array([[1, 1],
              [0, 1]])
print('A = :')
print(A)
B = np.array([[2, 0],
              [3, 4]])
print('B = :')
print(B)
print('A @ B = :')
print(A @ B)
print(A.dot(B))
print('B @ A = :')
print(B.dot(A))

c = np.random.random((2, 3))
print('c = :')
print(c)
print('c.sum() = :')
print(c.sum())
print('c.min() = :')
print(c.min())
print("c.max() = :")
print(c.max())
print('B.sum() = :')
print(B.sum())
